services:
  - type: web
    name: ecommerce-project
    runtime: python
    buildCommand: pip install -r requirement.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn ecommerce.wsgi:application
